apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.19.0+git
    operators.operatorframework.io/project_layout: unknown
  name: memcached-operator.v0.1.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Memcached
      name: memcacheds.cache.example.com
      version: v1
  description: Memcached Operator description. TODO.
  displayName: Memcached Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - cache.example.com
          resources:
          - memcacheds
          - memcacheds/status
          verbs:
          - get
          - list
          - watch
          - create
          - delete
          - patch
          - update
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
        serviceAccountName: memcached-quarkus-operator-operator
      deployments:
      - label:
          app.kubernetes.io/name: memcached-quarkus-operator-operator
          app.kubernetes.io/version: 0.0.1-SNAPSHOT
        name: memcached-quarkus-operator-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: memcached-quarkus-operator-operator
              app.kubernetes.io/version: 0.0.1-SNAPSHOT
          strategy: {}
          template:
            metadata:
              annotations:
                app.quarkus.io/build-timestamp: 2022-04-13 - 19:11:11 +0000
                app.quarkus.io/commit-id: 2394c189e6e1d20ce613bec6d9517bfef6ffae87
              labels:
                app.kubernetes.io/name: memcached-quarkus-operator-operator
                app.kubernetes.io/version: 0.0.1-SNAPSHOT
            spec:
              containers:
              - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: laxmikantbhaskarpandhare/memcached-quarkus-operator-operator:0.0.1-SNAPSHOT
                imagePullPolicy: Always
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/live
                    port: 8080
                    scheme: HTTP
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 10
                name: memcached-quarkus-operator-operator
                ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/ready
                    port: 8080
                    scheme: HTTP
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 10
                resources: {}
              serviceAccountName: memcached-quarkus-operator-operator
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - memcached-operator
  links:
  - name: Memcached Operator
    url: https://memcached-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.1.1
